AZURE_LOCATION: 'eastus'
RESOURCE_NAME_PREFIX: 'cloudy'
ENVIRONMENT_TAG: 'dev'
DEPLOYMENT_NAME: 'cloudy-apim-deployment'
VM_USERNAME: 'agent'
ACCOUNT_NAME: ${{ secrets.ACCOUNT_NAME }}
CICD_AGENT_TYPE: 'github'
CERT_TYPE: 'selfsigned'
